### ISSUE TITLE
problemas with the colors themes

### ISSUE THREAD

**Issue by matheusfcw** [notion-enhancer/extension#4] opened 2022-01-05 19:09 UTC
![image](https://user-images.githubusercontent.com/87440512/148274621-0a0f8e75-e664-4da3-a753-df95c1cbf2a5.png)

**Comment by dragonwocky** [comment] 2022-01-06 08:32
duplicate of https://github.com/notion-enhancer/notion-enhancer/issues/892 and the template was not properly filled out

please follow the [contributing guidelines](https://notion-enhancer.github.io/about/contributing/) or your bug reports / feature requests will be closed

**Closed as completed by dragonwocky** 2022-01-06 08:32 UTC
Labels: bug
